# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.
# Result: 4613732

def sum_even_fib(term_limit):
    older_term = 1
    old_term = 1
    this_term = 2
    result = 0
    while this_term <= term_limit:
        if not this_term % 2:
            result += this_term
        older_term = old_term
        old_term = this_term
        this_term = old_term + older_term
    return result

if __name__ == '__main__':
    """starts here"""
    print(sum_even_fib(4000000))